name: aagama_it #changing it will force you to change appname in import statement inside every .dart file.
description: Customer Support & Agent Management App

version: 2.0.0
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  audio_session: 0.1.10
  webview_cookie_manager: 2.0.6
  flutter_inappwebview: 5.4.3+7
  loading_indicator: 3.0.2
  webview_flutter: 3.0.4
  line_awesome_flutter: 2.0.0
  carousel_slider: 4.1.1
  stream_transform: 2.0.0
  flutter_rating_bar: 4.0.1
  flutter_expanded_tile: 0.3.6
  styled_text: 5.1.0
  restart_app: 1.1.0
  badges: 2.0.3
  dropdown_plus: 0.0.9
  cloud_functions: 4.4.0
  flutter_switch: 0.3.2
  pinch_zoom: 1.0.0
  eva_icons_flutter: 3.1.0
  flutter_cache_manager: 3.3.0
  rxdart: 0.27.5
  image_downloader: 0.31.0
  better_open_file: 3.6.4
  file_saver: 0.1.1
  gallery_saver: 2.3.2
  url_launcher: 6.1.3
  circular_countdown_timer: 0.2.1
  camera: 0.10.0+4
  oktoast: 3.1.5
  holding_gesture: 1.1.0
  flutter_emoji: 2.4.0
  pip_view: 0.9.6-nullsafety
  page_transition: 2.0.5
  wechat_assets_picker: 8.0.0
  image_editor: 1.0.2
  video_editor: 1.4.3
  flutter_image_compress: 1.1.0
  mime: 1.0.1
  video_compress:
    git:
      url: https://github.com/jonataslaw/videoCompress.git
      ref: a14d392
  link_preview_generator: 1.2.0
  google_mobile_ads: 2.0.1
  font_awesome_flutter: 9.2.0
  sms_autofill: 2.2.0
  receive_sharing_intent: 1.4.5
  firebase_crashlytics: 3.0.3
  async: 2.9.0
  emoji_picker_flutter: 1.3.1
  flutter_video_info: 1.2.0
  group_button: 3.3.1
  flutter_colorpicker: 0.6.1
  devicelocale: 0.5.4
  http_auth: 1.0.1
  cloud_firestore: 4.0.4
  flutter_cached_pdfview: 0.4.1
  fluttertoast: 8.0.9
  firebase_messaging: 14.0.3
  dio: 4.0.6
  cached_network_image: 3.2.1
  firebase_storage: 11.0.3
  device_info: 2.0.3
  file_picker: 5.2.2
  path_provider: 2.0.10
  path: 1.8.2
  flutter_sound: 9.2.13
  percent_indicator: 4.2.2
  string_validator: 0.3.0
  ntp: 2.0.0
  random_string: 2.3.1
  flutter_native_timezone: 2.0.0
  intl: 0.17.0
  connectivity: 3.0.6
  http: 0.13.4
  provider: 6.0.3
  firebase_auth: 4.1.0
  html: 0.15.0
  image_picker: 0.8.5+3
  universal_platform: 1.0.0+1
  flutter_linkify: 5.0.2
  dotted_border: 2.0.0+1
  diacritic: 0.1.3
  image_cropper: 1.5.1
  contacts_service: 0.6.3
  share: 2.0.4
  scoped_model: 2.0.0-nullsafety.0
  local_auth: 2.1.2
  crypto: 3.0.2
  encrypt: 5.0.1
  localstorage: 4.0.0+1
  photo_view: 0.12.0
  launch_review: 3.0.1
  overlay_support: 2.0.1
  jiffy: 4.1.0
  geolocator: 7.7.1
  video_player: 2.4.5
  video_thumbnail: 0.5.2
  chewie: 1.3.4
  media_info: 0.8.0
  firebase_core: ^2.15.1
  shared_preferences: 2.0.15
  permission_handler: 10.2.0
  agora_rtc_engine: 5.2.0
  translator: 0.1.7
  audioplayers: 0.20.1
  flutter_local_notifications: 9.8.0+1
  flutter_secure_storage: 5.0.2
  package_info: 2.0.2
  giphy_get: 3.1.0
  wakelock: 0.6.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  collection: ^1.15.0-nullsafety.4
  easy_search_bar: ^2.5.0
  get: ^4.6.5
  flutter_spinkit: ^5.2.0
  tabbed_view: ^1.16.0+1
  flutter_slidable: ^2.0.0
  #dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  flutter_driver:
    sdk: flutter
  test: ^1.16.8

  flutter_launcher_icons: ^0.9.2
flutter_icons:
  # android: "ic_launcher"
  ios: true
  image_path: "assets/appicon/appicon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - assets/fonts/
    - lib/Localization/json_languages/

  fonts:
    - family: Proxima-Nova-Alt-Bold
      fonts:
        - asset: assets/fonts/Proxima-Nova-Alt-Bold.otf
    - family: Proxima-Nova-Alt-Light
      fonts:
        - asset: assets/fonts/Proxima-Nova-Alt-Light.otf
    - family: Proxima-Nova-Alt-Thin
      fonts:
        - asset: assets/fonts/Proxima-Nova-Alt-Thin.otf
    - family: Proxima-Nova-Black
      fonts:
        - asset: assets/fonts/Proxima-Nova-Black.otf
    - family: Proxima-Nova-Bold
      fonts:
        - asset: assets/fonts/Proxima-Nova-Bold.otf
    - family: Proxima-Nova-Extrabold
      fonts:
        - asset: assets/fonts/Proxima-Nova-Extrabold.otf
    - family: Proxima-Nova-Regular
      fonts:
        - asset: assets/fonts/Proxima-Nova-Regular.otf
    - family: Proxima-Nova-Thin
      fonts:
        - asset: assets/fonts/Proxima-Nova-Thin.otf
    - family: Proxima-Nova-Semibold
      fonts:
        - asset: assets/fonts/Proxima-Nova-Semibold.otf
